### ISSUE TITLE
Lots of conflicts with Xamarin Forms Labs

### ISSUE THREAD

**Issue by henslecd** [xamarin/Monkey.Robotics#19]
I use Xamarin Forms Labs and there are few conflicts between the binaries.  

FWIW It might make more sense for you guys to help those guys out with this code.  Your code and samples fill a void, especially in the bluetooth section.

**Comment by conceptdev** [comment]
We love that the community extends Xamarin.Forms with projects like Labs, however we can't support each and every individual or group's community project. With libraries like Monkey.Robotics we want to provide cross-platform APIs for important mobile platform features (note that you can use Monkey.Robotics in regular Xamarin projects to provide the ability to write BLE in shared code, it's not just for Xamarin.Forms).
