### ISSUE TITLE
Does Monkey.Robotics support SPP for iOS?

### ISSUE THREAD

**Issue by chriseyhorn** [xamarin/Monkey.Robotics#50]
Trying to figure out if the Core.Bluetooth.LE supports Serial Port Profile for communication for iOS.

Thanks in advance,
Chris

**Comment by bryancostanich** [comment]
No. That's not part of Bluetooth LE, it's an older version of the spec (like BT 2.0), and isn't available on iOS unless you have signed their accessory developer legal contract. You can do SPP on Android however, and there is a sample here: https://blog.xamarin.com/hello-mr.-bond_agent_watch/
